### ISSUE TITLE
Initialize TypeScript with a sensible config

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-toolkit#1]
- [ ] Initialize npm project with typescript
- [ ] Add typedoc and other required libraries
- [ ] Add TypeScript configurations

- Will provide you with a basic config
- How do we do tree shaking (ESM) and how do we serve 2 different modules (ESM vs CommonJS)
- Is it better to move every export to a single file or keep them separated (https://github.com/qoretechnologies/reqore check for more 
- Find a good documentation tool that uses comments from code directly

**Comment by rishabhmalik759** [comment]
**@https://webpack.js.org/guides/tree-shaking/**

1. Tree shaking can be achieved using webpack, the general rules to achieve tree shaking are:

- Use ES2015 module syntax (i.e. import and export).

- Ensure no compilers transform your ES2015 module syntax into CommonJS modules (this is the default behavior of the popular Babel preset @babel/preset-env - see the [documentation](https://babeljs.io/docs/en/babel-preset-env#modules) for more details).

- Add a "sideEffects" property to your project's package.json file.

- Use the [production](https://webpack.js.org/configuration/mode/#mode-production) mode configuration option to enable [various optimizations](https://webpack.js.org/configuration/mode/#usage) including minification and tree shaking.

We can imagine our application as a tree. The source code and libraries you actually use represent the green, living leaves of the tree. Dead code represents the brown, dead leaves of the tree that are consumed by autumn. In order to get rid of the dead leaves, you have to shake the tree, causing them to fall.

2. Tree shaking can also be achieved by tsc by compiling the module with two different configurations. @https://stackoverflow.com/questions/63520203/how-does-esm-tree-shaking-dead-code-elimination-work.
![Image](https://user-images.githubusercontent.com/23454410/185926486-b036af84-da18-4a53-a966-76a8fa725d83.png)

**Comment by rishabhmalik759** [comment]
- @https://2ality.com/2019/10/hybrid-npm-packages.html

CommonJS and ESM modules hybrid packages can be achieved by:

- Conditional exports can be used to integrate both CommonJS and ESM modules. The directory structure updates as:


![Image](https://user-images.githubusercontent.com/23454410/185920605-c3bdd53f-f67b-491b-a801-4683fa0a4c86.png)

- deep-import ESM (it provides maximum backward compatibility 

![Image](https://user-images.githubusercontent.com/23454410/185920912-97f8e09b-af91-4181-9231-092e03e2f309.png)

- bare-import ESM ( Best to use with new packages that wants to provide backward compatibility )
 

![Image](https://user-images.githubusercontent.com/23454410/185921290-2818832f-232b-40c7-8233-1dc22dbb3401.png)

**Comment by rishabhmalik759** [comment]
@https://github.com/TypeStrong/typedoc
Typedoc can be a great library to create documentations it provides various annotations and documentation can be generated from the code comments itself. It also provides ways to customize the documentation css and views.
The result of the generated docs looks like this:

![Image](https://user-images.githubusercontent.com/23454410/185925402-6c047ab7-ce42-4706-949e-afb32413f6dd.png)
